### ISSUE TITLE
huawei mate30发送短信如果过长，应用闪退

### ISSUE THREAD

**Issue by grainrain** [yztz/MsgGo#3]
弹框显示，MsgGo屡次停止运行

**Comment by yztz** [comment]
yztz@hust.edu.cn

**Comment by grainrain** [comment]
> [yztz@hust.edu.cn](mailto:yztz@hust.edu.cn)

已发送 。说明：测试短信消息如果很短，比如  XXXX您好，我是XXXX。消息可以正常发送。但是消息体很长，就会出现前面说的应用闪退，并弹出框显示  “MsgGo屡次停止运行”

**Comment by yztz** [comment]
已测试，同mate30 pro机型，系统 HarmonyOS 2.0，似乎没有出现上述情况。

有没有条件，给出 adb 调试信息？

**Comment by yztz** [comment]
目前猜测可能是系统原因，因为消息体过长（> 70）会触发短信分片机制，这个东西可能涉及到系统

**Comment by grainrain** [comment]
> 已测试，同mate30 pro机型，系统 HarmonyOS 2.0，似乎没有出现上述情况。
> 
> 有没有条件，给出 adb 调试信息？

这个需要指导，如何调出adb信息。另外手机是mate30 不是mate 30pro ，两者之间有差异。

**Comment by yztz** [comment]
> > 已测试，同mate30 pro机型，系统 HarmonyOS 2.0，似乎没有出现上述情况。
> > 有没有条件，给出 adb 调试信息？
> 
> 这个需要指导，如何调出adb信息。另外手机是mate30 不是mate 30pro ，两者之间有差异。

下载adb：https://dl.google.com/android/repository/platform-tools-latest-windows.zip
手机usb连接电脑，打开调试模式，在命令行中输入adb logcat *:E
详细的请参考下网上

麻烦你了:)

**Comment by yztz** [comment]
> > adb 调试信息
> 
> 发你邮箱了

好的，另外请问你的系统版本是？

**Comment by yztz** [comment]
> > adb 调试信息
> 
> 发你邮箱了

请查收附件。

**Comment by grainrain** [comment]
> > > adb 调试信息
> > 
> > 
> > 发你邮箱了
> 
> 请查收邮箱附件。

测试通过，非常感谢

**Comment by grainrain** [comment]
> > > adb 调试信息
> > 
> > 
> > 发你邮箱了
> 
> 好的，另外请问你的系统版本是？

HarmonyOS 4.2.0
